name: CI setup
description: Boilerplate for setting up CI
inputs:
  registry-url:
    type: string
    required: false
runs:
  using: composite
  steps:
    - uses: voidzero-dev/setup-vp@313600b80b104eadebb9111787d37a2e83e014ca # v1.17.0
      with:
        node-version-file: ./package.json
        cache: true
        registry-url: ${{ inputs.registry-url }}
        sfw: true
        run-install: true
